# データベース
CREATE DATABASE IF NOT EXISTS LEARN_SPRING CHARACTER SET utf8mb4;

# ユーザー
CREATE USER ureadonly@localhost IDENTIFIED BY 'preadonly';
CREATE USER ureadwrite@localhost IDENTIFIED BY 'preadwrite';

# 権限設定
GRANT SELECT ON LEARN_SPRING.* TO ureadonly@localhost;
GRANT SELECT, UPDATE, INSERT, DELETE ON LEARN_SPRING.* TO ureadwrite@localhost;

/*
 * マスタテーブルのテーブル生成クエリ.
 */
# APIキーマスタ
CREATE TABLE IF NOT EXISTS LEARN_SPRING.M_API_KEY(API_KEY CHAR(8) PRIMARY KEY, EXPIRATION_DATE DATE);
INSERT INTO LEARN_SPRING.M_API_KEY( API_KEY, EXPIRATION_DATE ) value ( 't|6M!D.X', NULL );
INSERT INTO LEARN_SPRING.M_API_KEY( API_KEY, EXPIRATION_DATE ) value ( 'M2h)CAve', NOW() );
INSERT INTO LEARN_SPRING.M_API_KEY( API_KEY, EXPIRATION_DATE ) value ( 'eM8~pQtH', NOW() + INTERVAL 12 MONTH );

# ユーザーマスタ
CREATE TABLE IF NOT EXISTS LEARN_SPRING.M_USER(USER_NAME VARCHAR(50) PRIMARY KEY, API_KEY CHAR(8));
INSERT INTO LEARN_SPRING.M_USER( USER_NAME, API_KEY ) value ( 'JavaPokul' , 't|6M!D.X' );
INSERT INTO LEARN_SPRING.M_USER( USER_NAME, API_KEY ) value ( 'guest' , NULL );
INSERT INTO LEARN_SPRING.M_USER( USER_NAME, API_KEY ) value ( 'rtaba' , 'M2h)CAve' );

/*
 * トランザクションテーブルの生成クエリ.
 */
 